name: 'Your name here'
description: 'Import SBOMs into GitHub dependency submission API'
author: 'evryfs'
inputs:
  sbom-file:
    required: true
    description: 'Path to SBOM file'
runs:
  using: 'node16'
  main: 'dist/index.js'
